const allShare=[
    {
      shareName: "RELIANCE",
      isBse: false,
      percentage: 5.20,
      profitPercentage: 0.45,
      isUp: true,
      price: 2530.60,
    },
    {
      shareName: "WIPRO",
      isBse: true,
      percentage: -2.30,
      profitPercentage: -0.15,
      isUp: false,
      price: 412.45,
    },
    {shareName:"HDFCBANK",
      isBse:true,
      percentage:-6.05,
      profitPercentage:-0.35,
      isUp:false,
      price:1705.80
    },{shareName:"INFY",
      isBse:false,
      percentage:-11.00,
      profitPercentage:-0.69,
      isUp:false,
      price:1579.85
    },{shareName:"TCS",
      isBse:true,
      percentage:-8.75,
      profitPercentage:-0.35,
      isUp:true,
      price:3512.35
    },{shareName:"ONGC",
      isBse:false,
      percentage:0.62,
      profitPercentage:0.28,
      isUp:true,
      price:225.02
    },{shareName:"HINDUNILVR",
      isBse:true,
      percentage:-17.00,
      profitPercentage:-0.78,
      isUp:false,
      price:2175.85
    },{shareName:"GOLDBEES",
      isBse:false,
      percentage:-0.50,
      profitPercentage:-0.69,
      isUp:true,
      price:72.82
    },
    {
      shareName: "HCLTECH",
      isBse: false,
      percentage: 3.40,
      profitPercentage: 0.25,
      isUp: true,
      price: 1245.30,
    },
    {
      shareName: "BAJFINANCE",
      isBse: true,
      percentage: -4.10,
      profitPercentage: -0.28,
      isUp: false,
      price: 7002.90,
    },
    {
      shareName: "ICICIBANK",
      isBse: false,
      percentage: 2.50,
      profitPercentage: 0.20,
      isUp: true,
      price: 940.15,
    },
    {
      shareName: "LT",
      isBse: true,
      percentage: -1.75,
      profitPercentage: -0.10,
      isUp: false,
      price: 3450.00,
    },
    {
      shareName: "SBIN",
      isBse: false,
      percentage: 4.60,
      profitPercentage: 0.32,
      isUp: true,
      price: 596.80,
    },
    {
      shareName: "AXISBANK",
      isBse: true,
      percentage: -3.90,
      profitPercentage: -0.22,
      isUp: false,
      price: 1045.50,
    },
    {
      shareName: "ITC",
      isBse: false,
      percentage: 1.25,
      profitPercentage: 0.08,
      isUp: true,
      price: 410.75,
    },
    {
      shareName: "MARUTI",
      isBse: true,
      percentage: -5.50,
      profitPercentage: -0.40,
      isUp: false,
      price: 9745.65,
    },
    {
      shareName: "ADANIPORTS",
      isBse: false,
      percentage: 6.80,
      profitPercentage: 0.50,
      isUp: true,
      price: 1180.35,
    },
    {
      shareName: "TATAMOTORS",
      isBse: true,
      percentage: -3.10,
      profitPercentage: -0.25,
      isUp: false,
      price: 625.70,
    },];
    

    module.exports=allShare;